### ISSUE TITLE
Set drive state minor issue

### ISSUE THREAD

**Issue by ulmitov** [Naudit/pystorcli2#12]
Hi,

When setting drive.state= 'good' it fails (i don't have an output to paste right now)
since there is no 'good' state, only 'ugood' or 'unconfigured good'
while drive.state = 'offline'\'missing'\'online' works well, it makes a little confusion

Thanks

**Comment by ralequi** [comment]
hmm, the state setter expects a "valid state" in the raw str that storcli expects or, a DriveState valid enum.

I'm checking and maybe forcing to convert into `DriveState` may fix your issue

**Comment by ralequi** [comment]
Is this issue fixed? I checked there were a commit a few weeks ago but don't remember if enough or not

**Comment by ralequi** [comment]
Ok, I'm closing this for now...

Reopen if you find it fails again please.

Thanks!
