### ISSUE TITLE
INVALID_STATUS text is not really correct

### ISSUE THREAD

**Issue by ulmitov** [Naudit/pystorcli2#17]
Hi,
Regarding  this code in error.py
INVALID_STATUS = (
        255, '', 'Invalid status - used for polling command completion.')

It is a a bit misleading, not sure if 255 is same for all cases but i got this one:
```
storcli64 /c0/e252/s7 set good J
{
"Controllers":[
{
	"Command Status" : {
		"CLI Version" : "007.2408.0000.0000 Nov 15, 2022",
		"Operating system" : "Linux 5.15.0-25-generic",
		"Controller" : 0,
		"Status" : "Failure",
		"Description" : "Set Drive Good Failed.",
		"Detailed Status" : [
			{
				"Drive" : "/c0/e252/s7",
				"Status" : "Failure",
				"ErrCd" : 255,
				"ErrMsg" : "Operation not allowed."
			}
		]
	}
}
]
}
```

**Comment by ralequi** [comment]
hi @ulmitov !

I was in vacations, sorry for the delay.
Did you find anything more about why that "Invalid status - used for polling command completion" is happening ?

**Comment by ralequi** [comment]
Pushed to develop/master

**Comment by ulmitov** [comment]
verified the fix, thanks!!
